### ISSUE TITLE
Issue in HAL Beta installation

### ISSUE THREAD

**Issue by PhilippeRoux** [HALRobotics/Beta#10]
Hi guys,

After a complete installation of HAL Beta (no indicated issue so far), I opened Rhino & Grasshopper and received the following message : 

> Priority: Loader
> {
>   Impossible de trouver une partie du chemin d'accès 'C:\Users\phili\AppData\Local\HAL'.: System.IO.DirectoryNotFoundException: Impossible de trouver une partie du chemin d'accès 'C:\Users\phili\AppData\Local\HAL'.
>    à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    à System.IO.FileSystemEnumerableIterator`1.CommonInit()
>    à System.IO.Directory.EnumerateFiles(String path, String searchPattern)
>    à HAL.Web.Licenser..ctor()
>    à HAL.Web.Licenser.get_Instance()
>    à HAL.McNeel.Grasshopper1.Client.Loader.#nERpOc'$-Qi2\\dx\*CGAj{rG#.MoveNext()
> --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
>    à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    à HAL.Extensions.AsyncHelpers.<>c__DisplayClass0_0.<<RunSync>b__0>d.MoveNext()
>    à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    à System.IO.FileSystemEnumerableIterator`1.CommonInit()
>    à System.IO.Directory.EnumerateFiles(String path, String searchPattern)
>    à HAL.Web.Licenser..ctor()
>    à HAL.Web.Licenser.get_Instance()
>    à HAL.McNeel.Grasshopper1.Client.Loader.#nERpOc'$-Qi2\\dx\*CGAj{rG#.MoveNext()
> --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
>    à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    à HAL.Extensions.AsyncHelpers.<>c__DisplayClass0_0.<<RunSync>b__0>d.MoveNext()
> 
>   Exception
> }

Is this an issue that you already met?

Cheers

**Comment by sebandraos** [comment]
This should be fixed in the next update, coming shortly.
