### ISSUE TITLE
"pattern settings" component?

### ISSUE THREAD

**Issue by Ngm0505** [HALRobotics/Beta#100]
Greetings,

Does anybody knows how to display the "pattern settings" component? I have installed the package and reinstalled HAL but I am still getting the image below when I search for "pattern settings".
Thanks for your collaboration

![Picture1](https://user-images.githubusercontent.com/67653786/117729116-aeea8200-b1ea-11eb-9299-a8d4039772c8.png)

_Originally posted by @Ngm0505 in https://github.com/HALRobotics/Beta/discussions/99#discussioncomment-720836_

**Comment by thibaultschwartz** [comment]
Hi Ngm, you seem to be using the slicer in alpha version. This package has no illustrations at the moment: icons will be missing on all components related to this package, but everything will run nonetheless. We will add icons in later revisions when we settle the content of this package.
