### ISSUE TITLE
Activate Robotiq Gripper

### ISSUE THREAD

**Issue by sampson-young** [HALRobotics/Beta#102]
Hi HAL,

I am using the same Robotiq 2F-140 gripper for a similar take/release operation as  https://github.com/HALRobotics/Beta/issues/63.
After following https://github.com/HALRobotics/Beta/discussions/84 this tutorial, I used the same format but couldn't export the same format code. 
I don't have the code of  `TakeObject()`  `def TakeObject() :` and `ReleaseObject()` `def ReleaseObject() :` (the pic below).

![image](https://user-images.githubusercontent.com/37079727/118372678-c17a0800-b5aa-11eb-824c-6c3feabf250b.png)

After I import this code to the UR10 robot, it can not read the code `rq_move_and_wait_mm(1)` and `rq_move_and_wait_mm(40)` in the controller. It seems to need a `def` code or something else to let the controller know I am operating the gripper. 

Do you have any solution or idea about that?
This is the file. [take and release.zip](https://github.com/HALRobotics/Beta/files/6487896/take.and.release.zip)

Many thanks.

Yang

**Comment by tristangobin** [comment]
Hi Yang,

The custom action ``rq_move_and_wait_mm(1)`` and ``rq_move_and_wait_mm(40)`` are specific to a controller and how gripper or other tools are integrated in your cell. You have to integrate your methods or you can use the build in components to set controller output signal and deal with how much time you need to wait for the gripper to close or open. 

Usually integrator implement a set of methods on a controller and you can call them from the CustomAction component.

I hope it helps, 

Kind regards
