### ISSUE TITLE
Inconsistent behavior in wired connections when "shift-arrowing" through component states

### ISSUE THREAD

**Issue by bringley** [HALRobotics/Beta#11]
Sometimes, shared inputs between component states do not maintain their wired connections.

For example, the Run and Controller inputs of the Export component maintain their wired connections in both state 1 and state 2 of the component, but the Path input loses the wired connection despite being a shared input between the two states.

![wirecx](https://user-images.githubusercontent.com/31935790/31362314-c6cfaa80-ad25-11e7-8e8e-9aee399df089.gif)

The "shift-arrowing" through component states is a new Grasshopper paradigm, so I'm seeking clarification on what the expected behavior is in these situations.

Thanks!

**Comment by thibaultschwartz** [comment]
Fixed in next update.
