### ISSUE TITLE
HAL Not Opening in Grasshopper

### ISSUE THREAD

**Issue by acation** [HALRobotics/Beta#115]
### Description

I have tried installing and uninstalling HAL several times, and it will not load in Grasshopper. I have tried opening HAL in Rhino 5, 6, and 7. None of these will work as expected. When opening Grasshopper I get the following error in the Rhino command line:

HAL: Method not found: 'Unity.IUnityContainer Prism.Unity.Ioc.UnityContainerExtension.get_Instance()'.

Upon installation there are no apparent errors:
![image](https://user-images.githubusercontent.com/12834315/134277988-2bd98b4f-41e0-457e-b595-903398ca462d.png)
However, when I open Grasshopper I do not receive a prompt to login to HAL, and HAL does not show up in my GH toolbar. In my Libraries folder, there is a link file, presumably that will link to the ProgramData folder which appears to contain the correct files

![image](https://user-images.githubusercontent.com/12834315/134280895-4a1c1d7b-54d0-4111-a272-6fee64bea575.png)

![image](https://user-images.githubusercontent.com/12834315/134280924-025bd5c7-311e-4d85-bc27-1d0d23d608ef.png)

Here is the installation log:
[Installation.log](https://github.com/HALRobotics/Beta/files/7207588/Installation.log)

### Steps to Reproduce

1. Install HAL through the HAL Framework .exe
2. Open Rhino/Grasshopper

**Expected behavior:** HAL loads properly

**Actual behavior:** HAL does not load at all

**Reproduces how often:** 100%

### Versions

HAL Version 1.4.6-beta
Windows 10 
Version 20H2 
OS Build 19042.1237

**Comment by acation** [comment]
Sorry, was a duplicate, and realized this was a compatibility issue with Enscape

**Comment by tristangobin** [comment]
Glad you found it anayway. Enjoy programming robots !
