### ISSUE TITLE
HAL plugin disappeared from Grasshopper

### ISSUE THREAD

**Issue by XtreeE-PRO** [HALRobotics/Beta#120]
When running Rhinoceros and then Grasshopper, HAL is not displayed anymore in my plugins tab.

This message appears in Rhino

![image](https://user-images.githubusercontent.com/80822085/155317387-6e55ab4f-8206-4695-8ca9-934352567b0a.png)

I tried uninstalling and installing the latest version, but it has no effect.

Can you help ? Thanks.

**Comment by sebandraos** [comment]
Hi @XtreeE-PRO ,
Can you identify something that changed with your Rhino installation just before it stopped loading?

Can you please upload the data requested in https://github.com/HALRobotics/Beta/issues/69#issue-553403132 so we can take a look at what might be causing the issue. As requested in the issue template, it would also be useful to know which OS you are using, which version of Rhino, what extensions you have installed, etc.

Thanks
