### ISSUE TITLE
Turntable synchronization for multiple rotations

### ISSUE THREAD

**Issue by anjakunic** [HALRobotics/Beta#124]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in a minimal file that you can share if needed.
    * Checked that your issue isn't already filed: https://github.com/HALRobotics/Beta/issues?utf8=%E2%9C%93&q=is%3Aissue

### Description

[Dear HAL team, I am looking into using a turntable that is synchronized with the movements of the robot on a rail unit. I would like to rotate the turntable multiple times (e.g. 6 times back and forth). Do I need to create each time a new sync component and a new corresponding robot position, or could I repeat the same group of commands for instance with "repeat data"?

I tried synchronizing a "init" turntable position = 0 degrees rotation with an "init" robot position, and a "reinit" turntable position = 180 degrees rotation with a "reinit" robot position, and I created a corresponding list of robot operations (e.g. Init, mill, reinit, mill, init, mill, reinit, mill, etc.).

I receive an error message saying: Synchronization setting reuse found. Synchronization settings have been found in two distinct sequences of the same procedure. I attach my file for you to see it.]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get the exact version of the Framework and all installed extensions in the HAL -> About menu or via the installer. Please also include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration, files or data that might be necessary to reproduce the issue.
![Screenshot 2022-04-13 143050](https://user-images.githubusercontent.com/50530508/163180308-211b5c45-4766-47d1-af9b-b1d80600d115.png)
![Screenshot 2022-04-13 143110](https://user-images.githubusercontent.com/50530508/163180314-2721fb6f-37a7-4dda-a4c4-cf330cc2a286.png)

[https://www.dropbox.com/s/1t56sn56z88zcx4/CREATE%20KUKA%20setup%20%20-%20%20turntable%20rotating.gh?dl=0](url)

**Comment by anjakunic** [comment]
Hi Thibault, 
So I need to create 6 sync settings and 6 corresponding robot/turntable positions if I want to rotate the table 6 times back and forth? 

Thanks for your fast reply.

**Comment by thibaultschwartz** [comment]
![image](https://user-images.githubusercontent.com/7550189/163217771-38bcb633-7fa6-499f-bd27-9c737337cd8c.png)
As mentioned in the doc, you can supply a single sync settings for a set of following targets that will result in a single motion action. If you supply a tree of targets, you will need to generate one sync settings per branch.

**Comment by tristangobin** [comment]
Tip : 
use the alias in the component to directly have multiple synch settings (multiple ref, not just one duplicated). The use it in a data tree. Should work nicely.

**Comment by anjakunic** [comment]
Great, thanks for the tip. That worked nicely!

**Comment by thibaultschwartz** [comment]
Great, I am closing this thread as solved then. Please reopen if you encouter syncing issues with turntables again.
