### ISSUE TITLE
Export time optimise

### ISSUE THREAD

**Issue by yuyuko01** [HALRobotics/Beta#128]
Hello,
I contact you for technical support.

I notice that since 2 days, the speed of exportation became really slow…
For an object like a clover tube, the solving time seems normal (16.8m), but it took hours to finish the exportation(3.7h).
Could you please have a look at this issue? 😃

Looking forward to your feedback

**Comment by sebandraos** [comment]
Hi @yuyuko01 , thanks for reporting this.

We are investigating this internally, can reproduce the issue and will get a fix released as soon as possible.

**Comment by sebandraos** [comment]
![image](https://github.com/HALRobotics/Beta/assets/6084391/dfcd9118-0d56-4503-9ad1-67ef7b793604)

Internally fixed for ABB which will be ready via an update tomorrow. Please let us know how that works for you and we will propagate the changes to other brands.

**Comment by Yutyng** [comment]
:-D It is MUCH faster now, thank you.
