### ISSUE TITLE
Orientation de l Outil selon la normale au parcours outil

### ISSUE THREAD

**Issue by yuyuko01** [HALRobotics/Beta#130]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in a minimal file that you can share if needed.
    * Checked that your issue isn't already filed: https://github.com/HALRobotics/Beta/issues?utf8=%E2%9C%93&q=is%3Aissue

### Description
Orienter le Z de l outil selon la normale au parcours outil 

### Steps to Reproduce
1. Le Script proposé par Tristan oriente bien le Z de l outil selon la normale mais uniquement selon l axe des Y , 

**Expected behavior:** 
L outil doit s orienter sur les X et les Y comme dans les exemples suivants
exemples
https://drive.google.com/file/d/1wbV_OjwExN2JejSJaw6zNi4DJKjXvzow/view?usp=drive_link
https://drive.google.com/file/d/1eBlp0vLgc8t-FbtTkrgJDbTnh1hmUDel/view?usp=drive_link

**Actual behavior:** [What actually happens]
L outil ne s oriente que sur les Y

**Reproduces how often:** [What percentage of the time does it reproduce?]
Toujours

### Versions
alpha

### Additional Information
Script et polyline du parcours outils disponibles par mail ou en MP

**Comment by tristangobin** [comment]
Could you send us demo file at **the-team**

Thanks

**Comment by tristangobin** [comment]
I don't find any bug in the provided example. Target component seems to work as it should.
