### ISSUE TITLE
ABB and KUKA missing in the 

### ISSUE THREAD

**Issue by svenpfeiffer** [HALRobotics/Beta#131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Hello,
I have not used HAL for about 2 months, now I cannot find ABB and KUKA extensions as options in the installer any more.
I am using HAL 1.417 beta.
What could be the problem?
Thanks!

### Steps To Reproduce

1 Started installer - see screenshot

### Additional Information

![image](https://github.com/HALRobotics/Beta/assets/32133871/fc9cd351-dea2-4c13-b0bc-a595f67ce6fd)

**Comment by sebandraos** [comment]
Hi @svenpfeiffer , 
This looks like something corrupted your installation.
Can you please send us your Installation.log file and Extensions.config file from the HAL Installation folder so we can see what that might have been?
Then you can follow the complete uninstall tutorial here (https://docs.hal-robotics.com/Grasshopper/0-Administration-and-Setup/Contents.html#05-complete-uninstallation), reinstall and everything should work again.
Thanks,
Seb

**Comment by svenpfeiffer** [comment]
Hi, the complete uninstall worked :) thank you.

[
[Installation.log](https://github.com/HALRobotics/Beta/files/13227846/Installation.log)
](url)
