### ISSUE TITLE
Read Digital Input

### ISSUE THREAD

**Issue by avifcohen** [HALRobotics/Beta#134]
### Description

Hello, 
I'm working with Kuka Kr 50, 
I would like to read a digital input as a condition to set other digital and analog outputs.
Since there is no component of reading digital/analog input I would like to know if there is any recommendation or solution to solve it. 
My intention for workflow is
Read Digital Input 1 - (wait till true) 
than 
Set Digital Output 2, Set Analog Output 2. 
Thank you
Avi.

**Comment by tristangobin** [comment]
### Wait signal action
 You can use the Wait component with waiting signal option (the third one).

![image](https://github.com/HALRobotics/Beta/assets/8418539/d52b6b64-f95b-4016-9aa9-c5081d42e968)
We will add shortly some documentation on the wait signal component, missing at the moment.

### Custom action
You can use a custom action and directly code it and add it into your procedure.

```
WAIT FOR $IN[10]==TRUE 
```
Where IN[10] is your digital input index 10.

### Related doc (set signal and custom action)
Please see our documentation about custom action [here](https://docs.hal-robotics.com/Grasshopper/5-Advanced-Programming/Contents.html#55-custom-actions).

Please also check our documentation on how to change signals state [here.](https://docs.hal-robotics.com/Grasshopper/4-IO/Contents.html#42-change-a-signal-state)

**Comment by avifcohen** [comment]
Thank you!

**Comment by tristangobin** [comment]
Glad it helped!
I close this issue but feel free to open it if necessary.

**Comment by avifcohen** [comment]
Hi tristan, The component wait of my HAL version not include Wait signal only time and sync. my version is 1.5.4 
is there is something I missing? 
thank you

**Comment by tristangobin** [comment]
Ah. sorry, we did not release this yet (it was in my debug session). In that case, I suggest you use the custom action instead.
