### ISSUE TITLE
[BUG] <title>No package found by the name of 'Bifocals'.

### ISSUE THREAD

**Issue by ztc1111** [HALRobotics/Beta#139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

![1](https://github.com/HALRobotics/Beta/assets/77040719/c942bfaa-839b-4b02-ada8-8af250472e31)

### Steps To Reproduce

I encountered this problem when running the file, how should I solve it

**Comment by sebandraos** [comment]
I don't believe this has anything to do with us. I would check with whoever sent you the file whether any other plugins are required.

**Comment by thibaultschwartz** [comment]
Closing, as unrelated to HAL. Please reopen if necessary.
