### ISSUE TITLE
Target reachability is ambiguous

### ISSUE THREAD

**Issue by ldemt** [HALRobotics/Beta#14]
Hello,
Here is my installation configuration : 

HAL.McNeel.V5.1.0.17278.2-beta
HAL.ABB.1.0.17278.2-beta

In HAL5 the IK solver warnings were useful to check target reachability, highlighting red or orange color and further indications when there was problems with target reachability or large reorientations.

In HAL6 the Execute component allows to see the robot running even if some targets are unreachable. But I did not found obvious information that the toolpath I designed may not be valid due to target unreachability (like turning the robot in red color or displaying a warning pop-up).

So I believed the toolpath was valid and discovered in RobotStudio that some of the targets were not reachable.

**Comment by sebandraos** [comment]
This should be fixed in the latest updates. Please feel free to reopen if this is not the case.
