### ISSUE TITLE
[BUG] missing extensions in the HAL Robotics Framework

### ISSUE THREAD

**Issue by Cianelli** [HALRobotics/Beta#141]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description of the bug

Hey,
as you can see in the pasted image, I have a problem with finding the extensions in the HAL Robotics Framework Software.
Some time ago I already had installed the extensions successfully, but I recently had a problem with Enscape and HAL, but BEFORE I even did any changes to my system, the extensions were missing. I since then managed the Enscape problem. But the extensions are still missing. I downloaded the newest *.exe from the HAL user portal, re-installed the Plug-in, nothing seemed to bring them back.
Any idea why they disappeared or any solution to get them back?
Thanks in advance!
Yannic
![image](https://github.com/HALRobotics/Beta/assets/129599635/df8ba5b8-b666-4683-a051-275431a43c73)

### Steps To Reproduce

see in the description

**Comment by sebandraos** [comment]
Hi @Cianelli ,

This looks like a corrupted installation (possibly linked to Enscape but not sure). Could you please try a [complete uninstall](https://docs.hal-robotics.com/Overview/0-Administration-and-Setup/Contents.html#05-complete-uninstallation) and try again?

Thanks,

**Comment by Cianelli** [comment]
Hey, thanks, that worked for me just fine!

Greetings
Yannic


Von: Sebastian Andraos ***@***.***>
Gesendet: Dienstag, 28. Mai 2024 20:04
An: HALRobotics/Beta ***@***.***>
Cc: Yannic Schena ***@***.***>; Mention ***@***.***>
Betreff: [EXT] Re: [HALRobotics/Beta] [BUG] missing extensions in the HAL Robotics Framework (Issue #141)


Hi @Cianelli<https://github.com/Cianelli> ,

This looks like a corrupted installation (possibly linked to Enscape but not sure). Could you please try a complete uninstall<https://docs.hal-robotics.com/Overview/0-Administration-and-Setup/Contents.html#05-complete-uninstallation> and try again?

Thanks,
