### ISSUE TITLE
HAL: The file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies could not be loaded. Unable to find the specified file.

### ISSUE THREAD

**Issue by Indistudio01** [HALRobotics/Beta#142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

HAL suddenly disappeared from grasshopper.
Closed and reopened rhino there is no more HAL. 
It seems to have disappeared after doing update.
- I have already verified that there are no incompatible plugins.
- In the Libraries folder there is the file HAL.ghlink.
- I have cleanly uninstalled HAL and all files related to it and reinstalled everything.
- COFF is enabled
- The most recent version of .NET Framework is installed
- No BETA versions are installed
- I have already tried deleting all the files from the Libraries folder except HAL.ghlink

I really don't know what to do, I have read all the problems of others, but I can't find any solution.
Between today and tomorrow I should renew my license, but if it doesn't work.......

At this link you will find the folder C:\ProgramData\HAL.
https://we.tl/t-MF6KpoUW1Y

Windows version:
Windows 11 Pro edition
Version 23H2

HAL version:
HAL.McNeel.V5 1.5.45
HAL.ABB 1.5.39

Rhino 7:
Version 7 SR28
(7.28.23058.3001, 2023-02-27)

### Steps To Reproduce

Open Rhino
Open Grasshopper
Appear HAL: Non è stato possibile caricare il file o l'assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' o una delle relative dipendenze. Impossibile trovare il file specificato.

HAL doesn't exist

**Comment by sebandraos** [comment]
Hi @Indistudio01 , it looks like an installer update hadn't quite gone out and there was a mismatch with the other updates. Thanks for alerting us to the issue.
Could you try one more clean uninstall and reinstall and let us know if that fixes the problem? 
Thanks

**Comment by Indistudio01** [comment]
OK, I just reinstalled it and now it works. This time I also manually deleted the registry keys and also used a specific software to uninstall.

Please fix these errors and bugs, this is not the first time these problems have occurred. 
I lost almost the whole day's work to solve this problem!
