### ISSUE TITLE
Installer with incorrect feed path won't start anymore

### ISSUE THREAD

**Issue by tristangobin** [HALRobotics/Beta#145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Once you set a incorrect feed path the installer seems not to be able to start. It means it is impossible to fixe the feed if necessary. 

### Steps To Reproduce

1. Set an incorrect feed in installer
2. close and restart
3. installer starts but it will be stuck at loading windows after an error message validation.
![image](https://github.com/user-attachments/assets/c270db81-424d-44dc-8173-573480ab6658)
![image](https://github.com/user-attachments/assets/6670f459-7d65-4538-aa7e-761f990aa0e0)

**Comment by sebandraos** [comment]
Thanks for reporting.

Can you please send me your Extensions.config file from "%ProgramData%\HAL", privately if required, and I'll try to reproduce the issue on my end.

Thanks

**Comment by tristangobin** [comment]
I emailed you this.

 Thanks

**Comment by sebandraos** [comment]
Fixed
