### ISSUE TITLE
Display, Sequential solving and File naming

### ISSUE THREAD

**Issue by romainduballet** [HALRobotics/Beta#26]
Hello, 

You'll find attached a zip file of a little 3D print project that we managed to get working, while experiencing some minor inconveniences.

- The sequential method (solving settings) does not seem to work properly, with recursive method it's ok.

- When exporting the file with predeclaration in Rapid, we cannot manage to name it in a custom fashion, the default name being Main module, which is dangerously similar to the actual main module in Robot Studio.

- There seems to be a display problem in this particular file, when sometime the robot takes a long time in the corners. It maybe linked to the fairly high quantity of targets, or the interpolation settings. The rapid is correct, and the actual robot does not mark this type of pauses. 

Best regards

Romain
[Feddback.zip](https://github.com/HALRobotics/Beta/files/2044649/Feddback.zip)

**Comment by sebandraos** [comment]
I believe all of these issues are resolved in the latest releases but please reopen if that is not the case
