### ISSUE TITLE
Tutorial for configure HAL to work with external axis?

### ISSUE THREAD

**Issue by yijiangh** [HALRobotics/Beta#30]
Hi, I am wondering if we can have a tutorial on how to configure HAL to work with a 6-axis robot + linear track (prismatic joint)  setting? I am using HAL.McNeel 1.1.16-beta + HAL.ABB 1.1.11-beta.

With the linear track's geometry at hand, I was thinking about maybe this can be achieved by using the `create joint` and `assemble` component. A simple demo file could be extremely helpful. 

Not sure if this is the right place (bug tracker...) to ask for this but many thanks in advance.

**Comment by sebandraos** [comment]
External axes are not yet supported within the Framework. We are actively developing this feature and will be releasing a demo file alongside the feature release. I can't give any guarantees of timings at the moment but we should have it included in the beta in the next couple of months.

**Comment by sebandraos** [comment]
External axes are now supported. There are a few tutorials [here](https://docs.hal-robotics.com/) that should help, most of which have demo files.
