### ISSUE TITLE
Target number limitation

### ISSUE THREAD

**Issue by romainduballet** [HALRobotics/Beta#34]
Hello, 

On this file, it seems that the solving won't succeed if we augment the number of target per layer. More precisely, on the left there is a line division of 20 operated for the main path. 20 seems to be a maximum here and I am not sure why. It does not seem to depend neither of the overall width of the object, nor of the blend sizes. 

My computer has 16 Gb ram

Best regards 

Romain
[Dub_targetnumber_100718.zip](https://github.com/HALRobotics/Beta/files/2179564/Dub_targetnumber_100718.zip)

**Comment by sebandraos** [comment]
Thanks for reporting. This isn't directly related to the number of targets but rather the resulting distance between them. Please see #35 for details. Following one or both workarounds there should solve your problem.

**Comment by romainduballet** [comment]
Hey Seb, 

I understand this is not the number itself. However i tried to put the blend ratio at zero and it can"t solve. I may not have correctly understood the #35

**Comment by romainduballet** [comment]
Ok I get it, it worked with the blend orientation at zero (?)
