### ISSUE TITLE
Incorrect icon display on Windows 7

### ISSUE THREAD

**Issue by lionpeloux** [HALRobotics/Beta#37]
Hi,

Am I getting incorrect display of icons ? I've got strange controls icons everywhere ...

![capture d ecran 2018-09-11 a 12 23 40](https://user-images.githubusercontent.com/951626/45354356-a1097c80-b5bd-11e8-8a81-55bbc334934d.png)
![capture d ecran 2018-09-11 a 12 23 34](https://user-images.githubusercontent.com/951626/45354357-a1097c80-b5bd-11e8-94b4-84ac4ad91cca.png)

**Comment by lionpeloux** [comment]
Hello sebandros,

Here is my config :

`HAL 1.2.6 beta`
`Rhino 6 SR8`
`MACOS 10.13.6` 
`VMWare Fusion 10.1.0` with `WIN7 PRO SP1`

**Comment by thibaultschwartz** [comment]
The missing font is Segoe UI Symbol, which is now part of Win10. Win7 users must install https://support.microsoft.com/en-us/help/2729094/an-update-for-the-segoe-ui-symbol-font-in-windows-7-and-in-windows-ser
We'll embed the font just in case in the next update, although installing this update should fix the issue.

**Comment by lionpeloux** [comment]
Apparently this update is already installed on my WIN7 (the installer said ...). And the font is present in the /Font folder. But still I'm missing the icons.

<img width="1680" alt="capture d ecran 2018-09-12 a 15 38 52" src="https://user-images.githubusercontent.com/951626/45428730-249c9980-b6a2-11e8-9ba0-9c8b13d245e6.png">

**Comment by thibaultschwartz** [comment]
Are you still missing the icon in both the popup window and GH, or only GH?

**Comment by thibaultschwartz** [comment]
OK, let's test this again in a few days with the embedded font / next update, as I unfortunately cannot replicate this at the moment.

**Comment by sebandraos** [comment]
This should be fixed in the latest set of updates. Please reopen if that isn't the case
