### ISSUE TITLE
How to connect a robot arm to a linear unit (track) ?

### ISSUE THREAD

**Issue by lionpeloux** [HALRobotics/Beta#40]
Hello,

`HAL 1-2-6 beta`

I can't find how to properly connect a robot arm to a track in order to create a composed mechanism (A1 ... A6 + E1). Would you please propose an example file on this repo ?

You can download my GH definition [here](https://www.dropbox.com/s/jib5l0x6j5trhcq/HAL%20-%20arm%20with%20track.gh?dl=0).

<img width="1680" alt="capture d ecran 2018-09-12 a 10 22 19" src="https://user-images.githubusercontent.com/951626/45411916-c3f76780-b675-11e8-8c7a-7f79ab8411c9.png">

**Comment by sebandraos** [comment]
Closed as duplicate #30
