### ISSUE TITLE
Incorrect A1/A4/A6 orientations for KUKA arms ? 

### ISSUE THREAD

**Issue by lionpeloux** [HALRobotics/Beta#41]
Hi,

`HAL 1.2.6 beta`
`Rhino 6 SR8`
`VMWare Fusion 10.1.0`

I think the orientation of A1, A4 and A6 axis for KUKA arms in your catalog should be "flipped" to match kuka's convention of signs. I've checked several (eg. KR1000 titan) of your robot definitions and they are all the same. See images below.

Also, wouldn't it be more consistent to have the "axis zero positions" aligned (up or down) for A4 and A6 (see image 2) ?

<img width="1792" alt="capture d ecran 2018-09-12 a 12 05 20" src="https://user-images.githubusercontent.com/951626/45418325-7df5d000-b684-11e8-8351-d608b9baf4e5.png">

<img width="1680" alt="capture d ecran 2018-09-12 a 12 20 53" src="https://user-images.githubusercontent.com/951626/45419021-615a9780-b686-11e8-8e28-91c3169786e4.png">

<img width="1680" alt="capture d ecran 2018-09-12 a 12 21 07" src="https://user-images.githubusercontent.com/951626/45419027-64558800-b686-11e8-86eb-b621d83ff311.png">

**Comment by lionpeloux** [comment]
Ok, I wasn't aware of this singularity trick.

**Comment by sebandraos** [comment]
Our entire KUKA catalogue should now be up to date. Please feel free to reopen this issue if there are still issues
