### ISSUE TITLE
Improper behavior of preview when "Only draw preview geometry for selected objects" is enabled ?

### ISSUE THREAD

**Issue by lionpeloux** [HALRobotics/Beta#42]
Hi,

When the `"Only draw preview geometry for selected objects"` option is enabled in GH, every component that is selected should display in Rhino, disregarding if the preview is enabled or not for the said components. This is the standard preview behavior for GH components I've seen so far and I assume this is the expected behavior.

However, for several HAL components / parameters, if the `"Only draw preview geometry for selected objects"` option is enabled, only selected components which preview is **enabled** will display in Rhino viewport, not the ones with **disabled** preview.

It is the case at least for this components/params :

* Mechanism Param
* Part Param
* Target Comp

### Versions

`HAL 1.2.6 beta`
`Rhino 6 SR8`
`MACOS 10.13.6` 
`VMWare Fusion 10.1.0` with `WIN7 PRO SP1`

<img width="1680" alt="capture d ecran 2018-09-12 a 14 53 20" src="https://user-images.githubusercontent.com/951626/45426136-ac32da00-b69b-11e8-87ff-cea029c92185.png">
<img width="1680" alt="capture d ecran 2018-09-12 a 14 53 25" src="https://user-images.githubusercontent.com/951626/45426141-ae953400-b69b-11e8-88fc-eeea41230f5e.png">

**Comment by thibaultschwartz** [comment]
fixed in next update
