### ISSUE TITLE
Frame Properties Component

### ISSUE THREAD

**Issue by lionpeloux** [HALRobotics/Beta#43]
Hello,

Do you plan to add a component to retrieve the *properties* of a frame ?

Indeed, it would be very convenient to be able not only to construct frames from euler angles, quaternion ... but also to do the opposite and get the euler angles or quaternion of a given frame.

Thanks,

<img width="1680" alt="capture d ecran 2018-09-12 a 15 17 53" src="https://user-images.githubusercontent.com/951626/45427664-accd6f80-b69f-11e8-9c0a-3df88202b91b.png">

**Comment by thibaultschwartz** [comment]
Added in next release
