### ISSUE TITLE
Revolute joint preview : placement of the bounds

### ISSUE THREAD

**Issue by lionpeloux** [HALRobotics/Beta#45]
The preview of revolute joints is very convenient. May I suggest to improve the readability slightly by :

* cuting-off the bounds to 1 or 2 digits only ?
* orient the labels perpendicularly (and not tangent) to the circle ? (more readable I think)
* display values in deg and not in rad (questionable / In my view deg is more human readable)

<img width="1680" alt="capture d ecran 2018-09-13 a 08 34 39" src="https://user-images.githubusercontent.com/951626/45470972-e51c8e80-b72f-11e8-978a-d44d57495050.png">

**Comment by thibaultschwartz** [comment]
- agreed
- I centered it on the boundary and moved it a bit away (like the zero mark), it's simpler to read.
- agreed

It will be available in the next update.
