### ISSUE TITLE
Retrieve the plane of a reference frame ?

### ISSUE THREAD

**Issue by lionpeloux** [HALRobotics/Beta#46]
Hello,

Is it possible to retrieve the plane associated with a "reference frame" parameter ? I cannot see any component that can do that at the moment. Maybe a direct conversion to a GH_Plane in the future would be practical ?

<img width="1680" alt="capture d ecran 2018-09-13 a 12 10 37" src="https://user-images.githubusercontent.com/951626/45482444-5e2ade80-b74e-11e8-8bfb-ac062e422b87.png">

Moreover, how would you follow a frame that is attached to a given parent mechanism. For instance, how can you retrieve `$ROBROOT` at a specific PTP configuration/target in case of a linear track ?

![image](https://user-images.githubusercontent.com/951626/45482414-4d7a6880-b74e-11e8-994d-54f9a1f385e4.png)

Many thanks for your support

**Comment by lionpeloux** [comment]
Ok. But then how would you simulate the rotation of a part attached to (lets say) a turn table ?

**Comment by thibaultschwartz** [comment]
That's all done when the simulation runs. We'll post external axis tutorials when we fix a last few bugs, but the logic is the following:
- declare your parts and define their relationships using connections (Create Joint -> Connection)
- when joints are actuated or when the locations of one or more parts change for some reason, all impacted objects (parts linked by connections or joints) get their state updated. The display is then called to show this new state
- the "Execute" component has an extra input called "Environment", which takes objects to be redrawn systematically while the simulation runs
