### ISSUE TITLE
Controller Node throws error: 1. [Error] Line creation failed. Null or invalid argument: rotation.

### ISSUE THREAD

**Issue by yck011522** [HALRobotics/Beta#47]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in a minimal file that you can share if needed.
    * Checked that your issue isn't already filed: https://github.com/HALRobotics/Beta/issues?utf8=%E2%9C%93&q=is%3Aissue

### Description

Controller Node throws error: 1. [Error] Line creation failed. Null or invalid argument: rotation.

### Steps to Reproduce

1. Follow Video Tutorial up to 6:45: https://www.youtube.com/watch?v=2jnhRoDefW0&index=5&list=PLJK1IixFmcZe2vmfNQD_y-yBYFuT3kXlb

**Expected behavior:** No error

**Actual behavior:** Controller Node throws error: 1. [Error] Line creation failed. Null or invalid argument: rotation.

**Reproduces how often:** Every time on load

### Versions

Windows 10 Enterprise
Rhino Version 5 SR14 32-bit (5.14.522.8390, 5/22/2017)
Grasshopper 0.9.0076
HAL.McNeel.V5 1.2.6-beta
HAL.ABB 1.2.6-beta

### Additional Information

Curve is internalized in GH file for sharing
[unnamed.zip](https://github.com/HALRobotics/Beta/files/2393428/unnamed.zip)

**Comment by tristangobin** [comment]
Hi yck011522 , 
Thank's for sharing this. However, I did not acheave reproduce the error. What robot type and controller type did you use?
Could you try this definition? =>
[yck011522-01.zip](https://github.com/HALRobotics/Beta/files/2393459/yck011522-01.zip)

**Comment by yck011522** [comment]
Note that I also have Rhino 6 installed.

**Comment by yck011522** [comment]
![2018-09-18 17_48_56-grasshopper - yck011522-01](https://user-images.githubusercontent.com/1297653/45699792-24514200-bb6b-11e8-8470-2e65be2188ec.jpg)

**Comment by tristangobin** [comment]
What is your model unit in rhino? Could you, if it is not the case, open rhino 6 in mm and then open grasshopper and the definition? 
Thank's

**Comment by yck011522** [comment]
Okay, got it. It works in Rhino 6. 
I thought this version of HAL is for Rhino V.5. as that was shown in the description of the HAL installer.  Or it is?

**Comment by tristangobin** [comment]
Actually it is for both. Glad it now works. I close this issue. Thank's you for your report.

**Comment by yck011522** [comment]
Sure, thanks. I'm happy working with Rhino 6. But you may want to investigate why it doesn't work for Rhino 5, for many people are still sticking with Rhino 5..
