### ISSUE TITLE
Tool Frame Graphic Scale Issue

### ISSUE THREAD

**Issue by bringley** [HALRobotics/Beta#5]
The tool fixation plane and TCP are displaying much larger than they should.

![image](https://user-images.githubusercontent.com/31935790/31058663-32647a26-a6c5-11e7-9a44-7366b828e4c4.png)

Expected behavior is that these planes' scale is determined by the Grasshopper Preview Plane Size setting.

This issue only occurs when a Grasshopper file containing HAL Beta is opened prior to opening a Rhino file containing geometry being referenced into Grasshopper.

This issue does not occur if I first open the Rhino file containing geometry being referenced into Grasshopper, and then open the Grasshopper HAL Beta file.

This issue can be fixed by inputting a new value into the Grasshopper Preview Plane Size setting.

This issue occurs in the following Rhino version: Version 5 SR14 64-bit (5.14.522.8390, 05/22/2017)

And the following Grasshopper version: 0.9.0076

On the following operating system: Windows 10 Pro 1703 OS build 15063.608

Please advise and thank you for your time.

**Comment by thibaultschwartz** [comment]
Fixed in next update, thanks for reporting this.
