### ISSUE TITLE
Strange behavior for the first PTP target

### ISSUE THREAD

**Issue by lionpeloux** [HALRobotics/Beta#55]
Hi,

My config :
`HAL 1.2.10 beta`
`Rhino 6 SR8`
`MACOS 10.13.6` 
`VMWare Fusion 10.1.0` with `WIN7 PRO SP1`

Apparently when the first target is at the same position as the "default" mechanism position, the simulation behaves incorrectly : the robot wait in the default position for a certain period of time and does not start moving immediately to the next position, like if it was moving to the already achieved position.

Lionel

**Comment by sebandraos** [comment]
Corrected in new update
