### ISSUE TITLE
Access to IK results ?

### ISSUE THREAD

**Issue by lionpeloux** [HALRobotics/Beta#57]
Hi, 

My config :
`HAL 1.2.10 beta`
`Rhino 6 SR8`
`MACOS 10.13.6` 
`VMWare Fusion 10.1.0` with `WIN7 PRO SP1`

I am working on a wire stone cutting machine (2 prismatic dof + 1 rotational dof).
I would love to "IK solve" this custom mechanism in HAL and get access to the solved joint positions.
From there, It will be easy to write a small postprocessor of my own to feed the machine with GCode.

Would you be able to provide us with a component that will give us for each inputed target the solved position in the joint space ? This would give lots of flexibility for end users like me :)

Lionel

**Comment by tristangobin** [comment]
IK results are accessible through monitoring component.
