### ISSUE TITLE
Can't load robots from the catalog

### ISSUE THREAD

**Issue by lionpeloux** [HALRobotics/Beta#62]
Hi,

My config :
HAL 1.2.19 beta
Rhino 6 SR8
MACOS 10.13.6
VMWare Fusion 10.1.0 with WIN7 PRO SP1

I've just upgraded to HAL 1.2.19 beta and I can't load any robots from the catalog.
Is this a known problem ?

![Capture d’écran 2019-05-02 à 09 27 37](https://user-images.githubusercontent.com/951626/57061298-9884c400-6cbc-11e9-9135-7ce2013df3fa.png)

Lionel

**Comment by sebandraos** [comment]
Hi @lionpeloux , Can you please confirm that this issue is linked to COFF loading in the Grasshopper Developer Settings? i.e. If you turn COFF loading off, does the problem go away? This will help us narrow down the source of the problem.
Do you have any extensions installed?

**Comment by sebandraos** [comment]
We have managed to repro this error. It appears we have a upgraded a dependency that is causing this issue. A new build is currently running and should be live in the next few minutes. Please check version 1.2.20 and let us know if the problem persists.

**Comment by lionpeloux** [comment]
Hi seb,
I don't see the 1.2.20 update. Did it pass the build ?

**Comment by sebandraos** [comment]
It did but I forgot to approve it, apologies. It should be live imminently

**Comment by lionpeloux** [comment]
Ok, It's working now.
Thanks !
