### ISSUE TITLE
Robot script inside Grasshopper 

### ISSUE THREAD

**Issue by anjakunic** [HALRobotics/Beta#73]
Dear HAL team,

I would like to extract a resulting robot code into a panel inside Grasshopper. I remember this was possible in the old HAL version, but I don't seem to find a way to make it in the HAL robotics framework. Do you have any plans on integrating back this option?

**Comment by thibaultschwartz** [comment]
Hi,
You can use the "Disassemble" component to retrieve the parts and joints of a mechanism, in case you need to reference one in particular. What data are you looking to extract and in what purpose?

**Comment by thibaultschwartz** [comment]
Hi,
Apologies, I misunderstood your question in my previous reply. 
We added an output to the Export component recently which gives the path of all generated robot files, it allows users to use the Grasshopper "Read File" component to open the generated code file(s) and display them in GH like in HAL 5. It might not be public yet, in that case it will be in the next update we will be releasing over the next few weeks.
In the meantime you can use the "Export" component and browse to the folder you specified as a destination. Once you found your file, open it in notepad++, it will update when you export it again.

**Comment by sebandraos** [comment]
This should be fixed in the latest update but please reopen if need be.
