### ISSUE TITLE
Unrecognized objects

### ISSUE THREAD

**Issue by Ngm0505** [HALRobotics/Beta#74]
### Description

Greetings,
After building my model into the HAL framework, I get "Unrecognized obje
.jpg)
cts" error message when I try to open my file again. If I try to dowload the missing plugins, I get "Couldn't find HAL for Grasshopper (1.2.59.0)] and "Not all plug-ins were found on the package server".
You can find attached an screeshot of the errors.
Best,

![Error 2](https://user-images.githubusercontent.com/67653786/86161988-6401d780-bb0e-11ea-9da6-675c6c259b26.jpg)
![Error 1](https://user-images.githubusercontent.com/67653786/86161990-649a6e00-bb0e-11ea-92bc-0f606c308489)
![Error 2](https://user-images.githubusercontent.com/67653786/86161935-50ef0780-bb0e-11ea-9f5a-c5e6ec0a2f91.jpg)
![Error 1](https://user-images.githubusercontent.com/67653786/86161937-51879e00-bb0e-11ea-9c61-78b8a8fa36b5.jpg)

**Comment by thibaultschwartz** [comment]
Hi,
HAL must always be installed using the HAL installer, the Grasshopper package manager will **NOT** be able to install it.
I would suggest you uninstall and reinstall HAL.  Please make sure Rhino is closed when you do so, and that you have a stable internet connection.
Best,
T

**Comment by Ngm0505** [comment]
Hi Thibault,
Works better. 
Thank you,
