### ISSUE TITLE
Mesh Preview Clipping Issue in Rhino Viewport

### ISSUE THREAD

**Issue by bringley** [HALRobotics/Beta#8]
The mesh rendering of the robot/tool generated by components such as the HAL Execute component is demonstrating clipping issues in the Rhino viewport.

![image](https://user-images.githubusercontent.com/31935790/31081586-59063f44-a75a-11e7-8eca-53d2bedeb051.png)

This issue can be resolved by drawing a box around the extents of the mesh geometry.

![image](https://user-images.githubusercontent.com/31935790/31081626-77826b28-a75a-11e7-8e53-9dd9006c04a6.png)

I spoke with @AndrewHeumann about it and he says:
"I suspect this is due to not correctly setting the BoundingBox property during DrawViewportWires/DrawViewportMeshes method overrides on the components. The issue goes away as soon as there's a large enough object in the Rhino scene - the viewport clipping planes are affected by the bounding boxes of GH preview geometry but these must be calculated explicitly in component code."

This issue occurs in the following Rhino version: Version 5 SR14 64-bit (5.14.522.8390, 05/22/2017)

And the following Grasshopper version: 0.9.0076

On the following operating system: Windows 10 Pro 1703 OS build 15063.608

Please advise and thank you for your time.

**Comment by thibaultschwartz** [comment]
Fixed in next update, thanks for reporting this.
